# Generated by Django 5.2.2 on 2025-06-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredibilityCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('resat_pass_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('resat_pass', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('number_attempts', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CredibilityCodes_email', to='accounts.emails')),
                ('mobile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CredibilityCodes_mobile', to='accounts.mobiles')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBrowsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('ln', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.CharField(blank=True, max_length=60, null=True)),
                ('os', models.CharField(blank=True, max_length=60, null=True)),
                ('device', models.CharField(blank=True, max_length=60, null=True)),
                ('brand', models.CharField(blank=True, max_length=60, null=True)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('version', models.CharField(blank=True, max_length=60, null=True)),
                ('encrypted_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('close_pass', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('website', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserBrowsers_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('browser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPasswords_browser', to='accounts.userbrowsers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPasswords_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
