version: '3.8'

services:
  # Redis للـ Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sehaty
      POSTGRES_USER: sehaty_user
      POSTGRES_PASSWORD: t*FMRp^und*Cayw3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Django Web Application
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-@o$$p4$$wb#)@rt%!5bge2p-zc#cga*mfje$$el#=1vc=@n_)*g&
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=sehaty
      - DB_USER=sehaty_user
      - DB_PASSWORD=t*FMRp^und*Cayw3
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    restart: unless-stopped

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A core worker -l info --concurrency=2
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-@o$p4$wb#)@rt%!5bge2p-zc#cga*mfje$el#=1vc=@n_)*g&
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=sehaty
      - DB_USER=sehaty_user
      - DB_PASSWORD=t*FMRp^und*Cayw3
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped

  # Celery Beat (للـ scheduled tasks)
  celery_beat:
    build: .
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-@o$p4$wb#)@rt%!5bge2p-zc#cga*mfje$el#=1vc=@n_)*g&
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=sehaty
      - DB_USER=sehaty_user
      - DB_PASSWORD=t*FMRp^und*Cayw3
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped

  # Flower للـ monitoring Celery (اختياري)
  flower:
    build: .
    command: celery -A core flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  default:
    name: sehaty_network